"""Add notification preferences to User model

Revision ID: 1e9ba2edd87c
Revises: 6af96cd1f439
Create Date: 2025-03-30 23:02:09.784875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9ba2edd87c'
down_revision = '6af96cd1f439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expiry_date', table_name='items')
    op.drop_index('idx_user_expiry', table_name='items')
    op.drop_index('idx_user_status', table_name='items')
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sms_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('in_app_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'in_app_notifications')
    op.drop_column('users', 'sms_notifications')
    op.drop_column('users', 'email_notifications')
    op.create_index('idx_user_status', 'items', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_expiry', 'items', ['user_id', 'expiry_date'], unique=False)
    op.create_index('idx_expiry_date', 'items', ['expiry_date'], unique=False)
    # ### end Alembic commands ###
