"""Add database indexes

Revision ID: 6af96cd1f439
Revises: 
Create Date: 2025-03-30 20:28:33.710443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6af96cd1f439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_expiry_date', 'items', ['expiry_date'], unique=False)
    op.create_index('idx_user_expiry', 'items', ['user_id', 'expiry_date'], unique=False)
    op.create_index('idx_user_status', 'items', ['user_id', 'status'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('idx_user_status', table_name='items')
    op.drop_index('idx_user_expiry', table_name='items')
    op.drop_index('idx_expiry_date', table_name='items')
    # ### end Alembic commands ###
