"""Add password_reset_token to User model

Revision ID: bb1ce8cf50c2
Revises: 1e9ba2edd87c
Create Date: 2025-03-31 11:29:44.034220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1ce8cf50c2'
down_revision = '1e9ba2edd87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
